language: node_js
node_js:
  - "10.15.2"
addons:
  code_climate:
    repo_token: jMt2mhqfAqpBTIqr7/+mCuBWEHHm2v4l+bsR4hICC+o0fiY0ac6thDnlhrsHBGOUK6QSmX1mVSAe5rYh/krwAFiWXgNJpC7q3NUhKn8tnLyzn1Jvs4kNqVAqL7D75dhYSAHBqgNFM8lvrCgHw4RXi+ceaMH2TKL12TUIyHoTJsZCq3JDjFkITCvAvU8dxdikLxkvKGXZ8cP/Q21dxvoqhxrJCnOEq78Sv9B/r07ABqAK4i2AQ/TPsGO1SUFLc9NfcrIUEv2zTfl8vIpEXY4+L+JwYoZOY9IsupNtYC2rq+yXAoqFNvWh13EyINlec7JM5YHezQkWkLEMgXbMzYeHpfaPcIyrtbupsCHqxtcsUXJRQoOTc/4eGTwolZaqyPjxFrsa6S5fGrwVPA8dPI7GEsRVHODN+H03DyWSIb9j1cMOLKsu6O23v7yTj7S0Z7y8PQQsTtRMrI0PIap4xks37ZBZGY1twmL2LZzyajUs+3ge2IXeZ4gMyY05nKqPJ3lYEt5M2ON6Cx+cGtXm8g5EmTUMfpnTNBC8YR7hnMH4T3SLKpJGKT59bjpjZva8tltegFeiNFvo5kh05snEyoBuGuE5Mot6E0P451OBjn4MxyGh6hbBfx1t4+JCr7ORWcWvvq9FxJ55yinOzM26H/+tXFYGRYF+kdaaL9YTRhO7Jjg=
before_script:
  - npm install
script:
  npm test
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
