language: node_js
node_js:
- 10.15.2
addons:
  code_climate:
    repo_token:
      secure: kzzq1b0U5s06vOLkjKSMkWQl7H+Kd+dbXl4B446X7fBp0H1qCpdRPgiAInEH5h1VRjura4290ooZH2f4vY6rUTFKZB+mNmrgrmst22tMgAt/LcxSWFRr3miX7Vt3Gnc0AZ48tGV+ET0tPDRYYWqJI4jTlaJHrf9tGBgUEuNgS0344qJ8O/9XigM+j4VZK4dZFomTgdLMYkEs5ul5lLLHsM/+w790A7hDRL0S86w+JjnMnUFekm9XCIQbdTcJHroZGIQX8zSlPMmyu2d0V85uK5m79DWZCoxQLuUO94H8tI4UawZnBQjs3kcUwCzudhnBHi3xP+UCfK5qQyHcxLxXdlGY1LmdcC+be8LHWTP56mrJjXMwcYHJEjVLlUBCQeeBi3qe1NPvggxvXxVejTp7gdrxKZ+dfX5Knv70HZFROaNtTsaFJfI5dVSfS0bDESHF0THjst94RWHbnCqpHZj6cOZP7pKgfrICBiErKHkeKLlEHW8B/voKm/R6Ob9gRaM+6sTMHg0xU+W/S56nTCF/sV+HzXV/R8uS6BRCNXHSeqo+W3NP9QgdVrXs5npuatUFj2NCN8imUCSOleXhx1iQByPyCdyw4lgm7Xz3K2u3g7wD6LaHp/oTp9/OLw0Cm1SMtmjWvhw5D7c+fnGSA9ZVR7DPMgfJan2iuBqHn7dFNMU=
before_script:
- openssl aes-256-cbc -K $encrypted_151ea4390417_key -iv $encrypted_151ea4390417_iv -in test/PandoraCredentials.json.enc -out test/PandoraCredentials.json -d
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
install:
- npm install
script:
  npm test
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
